# model:
#   name: "ElasticNet"
#   alpha: 0.4
#   l1_ratio: 0.1
# data_transformation:
#   - name: TestTrainSpitter
#   - name: StandardScaler


model:
  name: "ElasticNet"
  alpha: 0.6
  l1_ratio: 0.4

data_transformation:
  - name: TrainTestSplitterSK
    test_size: 0.25
  - name: StandardScalerSK